### ISSUE TITLE
 If put property  "callback_url" in  method createSMS it crashes.

### ISSUE THREAD

**Issue by mephistopheles1010** [bsgworld/bsg-nodejs#2]
Wrong check property 'callback_url' in file police.js, method 'createSMS'
File police.js, method createSMS, line 284: '!patterns.url.match( fields.callback_url ) ){' , need to replace with '!patterns.url.test( fields.callback_url ) ){', because 'patterns.url' is RegExp and not contain method 'match', need to replace it with method 'test'. Or some other fix...
Error description:
TypeError: patterns.url.match is not a function
    at Object.createSMS (/path/to/project/node_modules/bsg-nodejs/lib/police.js:284:19)
    at /path/to/project/node_modules/bsg-nodejs/lib/bsg.js:154:32
    at Array.forEach (<anonymous>)
    at Object.createSMS (/path/to/project/node_modules/bsg-nodejs/lib/bsg.js:152:11)
    ...

**Comment by Naurzalin** [comment]
Thank you, fixed.
